name: taller_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  image_picker: ^1.1.2
  supabase_flutter: ^2.9.1
  url_launcher: ^6.1.10   
  youtube_player_flutter: ^8.0.0
  mobile_scanner: ^7.0.1
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data.json
